name: Build Angular app and deploy to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js in the ARCrypt.UI directory
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use a compatible version for your Angular project

    # Install dependencies inside ARCrypt.UI
    - name: Install Dependencies
      run: npm install
      working-directory: ARCrypt.UI  # Run this inside the ARCrypt.UI folder

    # Install Angular CLI inside ARCrypt.UI
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      working-directory: ARCrypt.UI  # Run this inside the ARCrypt.UI folder

    # Build the Angular app inside ARCrypt.UI
    - name: Build the Angular App
      run: ng build --output-path docs --configuration production --base-href /arcrypt/
      working-directory: ARCrypt.UI  # Run this inside the ARCrypt.UI folder



    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ARCrypt.UI/docs/browser  # Path to the built Angular app inside ARCrypt.UI
